# FROM node:18.17.1
# FROM node:18.17.1-slim

# Use a Debian-based image for better compatibility
# FROM node:20-bullseye as builder
# FROM node:22.17.0-bullseye-slim as builder
# FROM node:24.3.0-bookworm as builder
# FROM node:24.3.0-bookworm-slim as builder
# FROM node:24.3.0-alpine3.21 as builder

FROM node:22.17.0-bullseye


WORKDIR /opt/app/
COPY package*.json ./
RUN npm install
COPY . .


# ARG REACT_APP_API_URL=https://api.hyag.org/v1
# ENV REACT_APP_API_URL=$REACT_APP_API_URL
# RUN echo REACT_APP_API_URL=$REACT_APP_API_URL

# ARG REACT_APP_ACCOUNT_START=/chat
# ENV REACT_APP_ACCOUNT_START=$REACT_APP_ACCOUNT_START
# RUN echo REACT_APP_ACCOUNT_START=$REACT_APP_ACCOUNT_START

# ARG REACT_APP_SYNTHETIC_COMPONENTS='{}'
# ENV REACT_APP_SYNTHETIC_COMPONENTS=$REACT_APP_SYNTHETIC_COMPONENTS
# RUN echo REACT_APP_SYNTHETIC_COMPONENTS=$REACT_APP_SYNTHETIC_COMPONENTS

# ARG REACT_APP_CHAT_ENABLE=true
# ENV REACT_APP_CHAT_ENABLE=$REACT_APP_CHAT_ENABLE
# RUN echo REACT_APP_CHAT_ENABLE=$REACT_APP_CHAT_ENABLE

# ARG REACT_APP_TALK_ENABLE=true
# ENV REACT_APP_TALK_ENABLE=$REACT_APP_TALK_ENABLE
# RUN echo REACT_APP_TALK_ENABLE=$REACT_APP_TALK_ENABLE

# ARG REACT_APP_MAP_ENABLE=true
# ENV REACT_APP_MAP_ENABLE=$REACT_APP_MAP_ENABLE
# RUN echo REACT_APP_MAP_ENABLE=$REACT_APP_MAP_ENABLE

# ARG REACT_APP_MEET_ENABLE=true
# ENV REACT_APP_MEET_ENABLE=$REACT_APP_MEET_ENABLE
# RUN echo REACT_APP_MEET_ENABLE=$REACT_APP_MEET_ENABLE

# ARG REACT_APP_HIVE_ENABLE=true
# ENV REACT_APP_HIVE_ENABLE=$REACT_APP_HIVE_ENABLE
# RUN echo REACT_APP_HIVE_ENABLE=$REACT_APP_HIVE_ENABLE

# ARG REACT_APP_FLOW_ENABLE=true
# ENV REACT_APP_FLOW_ENABLE=$REACT_APP_FLOW_ENABLE
# RUN echo REACT_APP_FLOW_ENABLE=$REACT_APP_FLOW_ENABLE

# ARG REACT_APP_FLOW_URL=https://langflow.hyag.org
# ENV REACT_APP_FLOW_URL=$REACT_APP_FLOW_URL
# RUN echo REACT_APP_FLOW_URL=$REACT_APP_FLOW_URL

# ARG REACT_APP_NODE_ENABLE=true
# ENV REACT_APP_NODE_ENABLE=$REACT_APP_NODE_ENABLE
# RUN echo REACT_APP_NODE_ENABLE=$REACT_APP_NODE_ENABLE

# ARG REACT_APP_NODE_URL=https://node.hyag.org
# ENV REACT_APP_NODE_URL=$REACT_APP_NODE_URL
# RUN echo REACT_APP_NODE_URL=$REACT_APP_NODE_URL

# ARG REACT_APP_CODE_ENABLE=true
# ENV REACT_APP_CODE_ENABLE=$REACT_APP_CODE_ENABLE
# RUN echo REACT_APP_CODE_ENABLE=$REACT_APP_CODE_ENABLE

# ARG REACT_APP_CODE_URL=https://ide.hyag.org
# ENV REACT_APP_CODE_URL=$REACT_APP_CODE_URL
# RUN echo REACT_APP_CODE_URL=$REACT_APP_CODE_URL

# ARG REACT_APP_BUILD_ENABLE=true
# ENV REACT_APP_BUILD_ENABLE=$REACT_APP_BUILD_ENABLE
# RUN echo REACT_APP_BUILD_ENABLE=$REACT_APP_BUILD_ENABLE

# ARG REACT_APP_BUILD_URL=https://autogen.hyag.org
# ENV REACT_APP_BUILD_URL=$REACT_APP_BUILD_URL
# RUN echo REACT_APP_BUILD_URL=$REACT_APP_BUILD_URL

# ARG REACT_APP_OPEN_ENABLE=true
# ENV REACT_APP_OPEN_ENABLE=$REACT_APP_OPEN_ENABLE
# RUN echo REACT_APP_OPEN_ENABLE=$REACT_APP_OPEN_ENABLE

# ARG REACT_APP_OPEN_URL=https://open.hyag.org
# ENV REACT_APP_OPEN_URL=$REACT_APP_OPEN_URL
# RUN echo REACT_APP_OPEN_URL=$REACT_APP_OPEN_URL

# ARG REACT_APP_NOTE_ENABLE=true
# ENV REACT_APP_NOTE_ENABLE=$REACT_APP_NOTE_ENABLE
# RUN echo REACT_APP_NOTE_ENABLE=$REACT_APP_NOTE_ENABLE

# ARG REACT_APP_NOTE_URL=https://note.hyag.org/lab?token=my-token-abc
# ENV REACT_APP_NOTE_URL=$REACT_APP_NOTE_URL
# RUN echo REACT_APP_NOTE_URL=$REACT_APP_NOTE_URL

# ARG REACT_APP_SELL_ENABLE=true
# ENV REACT_APP_SELL_ENABLE=$REACT_APP_SELL_ENABLE
# RUN echo REACT_APP_SELL_ENABLE=$REACT_APP_SELL_ENABLE

# ARG REACT_APP_SELL_URL=https://odoo-proxy.hyag.org
# ENV REACT_APP_SELL_URL=$REACT_APP_SELL_URL
# RUN echo REACT_APP_SELL_URL=$REACT_APP_SELL_URL

# ARG REACT_APP_TRAIN_ENABLE=true
# ENV REACT_APP_TRAIN_ENABLE=$REACT_APP_TRAIN_ENABLE
# RUN echo REACT_APP_TRAIN_ENABLE=$REACT_APP_TRAIN_ENABLE

# ARG REACT_APP_TRAIN_URL=https://playwright.hyag.org/vnc.html
# ENV REACT_APP_TRAIN_URL=$REACT_APP_TRAIN_URL
# RUN echo REACT_APP_TRAIN_URL=$REACT_APP_TRAIN_URL

# ARG REACT_APP_DOCS_ENABLE=true
# ENV REACT_APP_DOCS_ENABLE=$REACT_APP_DOCS_ENABLE
# RUN echo REACT_APP_DOCS_ENABLE=$REACT_APP_DOCS_ENABLE

# ARG REACT_APP_DOCS_URL=https://docs.hyag.org
# ENV REACT_APP_DOCS_URL=$REACT_APP_DOCS_URL
# RUN echo REACT_APP_DOCS_URL=$REACT_APP_DOCS_URL

# ARG REACT_APP_XMPP_HOST=x.hyag.org
# ENV REACT_APP_XMPP_HOST=$REACT_APP_XMPP_HOST
# RUN echo REACT_APP_XMPP_HOST=$REACT_APP_XMPP_HOST

# ARG REACT_APP_XMPP_BOSH_SERVICE_URL=https://x.hyag.org/http-bind
# ENV REACT_APP_XMPP_BOSH_SERVICE_URL=$REACT_APP_XMPP_BOSH_SERVICE_URL
# RUN echo REACT_APP_XMPP_BOSH_SERVICE_URL=$REACT_APP_XMPP_BOSH_SERVICE_URL

# ARG REACT_APP_XMPP_DISCOVER_CONNECTION_METHODS=true
# ENV REACT_APP_XMPP_DISCOVER_CONNECTION_METHODS=$REACT_APP_XMPP_DISCOVER_CONNECTION_METHODS
# RUN echo REACT_APP_XMPP_DISCOVER_CONNECTION_METHODS=$REACT_APP_XMPP_DISCOVER_CONNECTION_METHODS

# ARG REACT_APP_XMPP_WEBSOCKET_URL=wss://x.hyag.org/xmpp-websocket
# ENV REACT_APP_XMPP_WEBSOCKET_URL=$REACT_APP_XMPP_WEBSOCKET_URL
# RUN echo REACT_APP_XMPP_WEBSOCKET_URL=$REACT_APP_XMPP_WEBSOCKET_URL

# ARG REACT_APP_XMPP_MUC_HOST=g.hyag.org
# ENV REACT_APP_XMPP_MUC_HOST=$REACT_APP_XMPP_MUC_HOST
# RUN echo REACT_APP_XMPP_MUC_HOST=$REACT_APP_XMPP_MUC_HOST

# ARG REACT_APP_XMPP_SHARE_HOST=f.hyag.org
# ENV REACT_APP_XMPP_SHARE_HOST=$REACT_APP_XMPP_SHARE_HOST
# RUN echo REACT_APP_XMPP_SHARE_HOST=$REACT_APP_XMPP_SHARE_HOST

# ARG REACT_APP_SHARE_URL_PREFIX=https://x.hyag.org/file_share/
# ENV REACT_APP_SHARE_URL_PREFIX=$REACT_APP_SHARE_URL_PREFIX
# RUN echo REACT_APP_SHARE_URL_PREFIX=$REACT_APP_SHARE_URL_PREFIX

# ARG REACT_APP_JITSI_DOMAIN=jitsi.hyag.org
# ENV REACT_APP_JITSI_DOMAIN=$REACT_APP_JITSI_DOMAIN
# RUN echo REACT_APP_JITSI_DOMAIN=$REACT_APP_JITSI_DOMAIN

# ARG REACT_APP_MOBILE_ENABLE=true
# ENV REACT_APP_MOBILE_ENABLE=$REACT_APP_MOBILE_ENABLE
# RUN echo REACT_APP_MOBILE_ENABLE=$REACT_APP_MOBILE_ENABLE

# ARG REACT_APP_MOBILE_WEB_APP_URL=https://m.hyag.org/
# ENV REACT_APP_MOBILE_WEB_APP_URL=$REACT_APP_MOBILE_WEB_APP_URL
# RUN echo REACT_APP_MOBILE_WEB_APP_URL=$REACT_APP_MOBILE_WEB_APP_URL

# ENV VITE_USE_WORKERS=false
# ENV NODE_ENV=production

RUN npm run build

# RUN mkdir -p /opt/ssl/ && openssl req -x509 -newkey rsa:4096 -keyout /opt/ssl/tls.key -out /opt/ssl/tls.crt -days 9999 -nodes -subj "/CN=localhost"
# RUN mkdir -p /opt/ssl/ && openssl req -x509 -newkey rsa:4096 -keyout /opt/ssl/tls.key -out /opt/ssl/tls.crt -days 9999 -nodes -subj "/CN=selfdev-web.dev.local"

EXPOSE 9099
# ARG BUILD_VERSION=0.0.1
# RUN npx json -I -f package.json -e "this.version='$BUILD_VERSION'"
# CMD ["npm", "start"]
CMD ["npm", "run", "serve"]
# CMD ["npm", "run", "serve:ssl"]

# Production image
# FROM nginx:alpine
# COPY --from=builder /opt/app/build /usr/share/nginx/html
