import React, { useState } from 'react'
import { isEmpty } from 'lodash'
import {
  Form,
  Dropdown,
  Label,
} from 'semantic-ui-react'
import { useTranslation } from 'react-i18next'

import { useIndexContext } from './IndexContext'

export function useCountries() {
  const { t } = useTranslation('Countries')

  return [
    {
      "key": "af",
      "value": "af",
      "flag": "af",
      "text": t("Afghanistan"),
    },
    {
      "key": "al",
      "value": "al",
      "flag": "al",
      "text": t("Albania"),
    },
    {
      "key": "dz",
      "value": "dz",
      "flag": "dz",
      "text": t("Algeria"),
    },
    {
      "key": "as",
      "value": "as",
      "flag": "as",
      "text": t("American Samoa"),
    },
    {
      "key": "ad",
      "value": "ad",
      "flag": "ad",
      "text": t("Andorra"),
    },
    {
      "key": "ao",
      "value": "ao",
      "flag": "ao",
      "text": t("Angola"),
    },
    {
      "key": "ai",
      "value": "ai",
      "flag": "ai",
      "text": t("Anguilla"),
    },
    {
      "key": "aq",
      "value": "aq",
      "flag": "aq",
      "text": t("Antarctica"),
    },
    {
      "key": "ag",
      "value": "ag",
      "flag": "ag",
      "text": t("Antigua and Barbuda"),
    },
    {
      "key": "ar",
      "value": "ar",
      "flag": "ar",
      "text": t("Argentina"),
    },
    {
      "key": "am",
      "value": "am",
      "flag": "am",
      "text": t("Armenia"),
    },
    {
      "key": "aw",
      "value": "aw",
      "flag": "aw",
      "text": t("Aruba"),
    },
    {
      "key": "au",
      "value": "au",
      "flag": "au",
      "text": t("Australia"),
    },
    {
      "key": "at",
      "value": "at",
      "flag": "at",
      "text": t("Austria"),
    },
    {
      "key": "az",
      "value": "az",
      "flag": "az",
      "text": t("Azerbaijan"),
    },
    {
      "key": "bs",
      "value": "bs",
      "flag": "bs",
      "text": t("Bahamas"),
    },
    {
      "key": "bh",
      "value": "bh",
      "flag": "bh",
      "text": t("Bahrain"),
    },
    {
      "key": "bd",
      "value": "bd",
      "flag": "bd",
      "text": t("Bangladesh"),
    },
    {
      "key": "bb",
      "value": "bb",
      "flag": "bb",
      "text": t("Barbados"),
    },
    {
      "key": "by",
      "value": "by",
      "flag": "by",
      "text": t("Belarus"),
    },
    {
      "key": "be",
      "value": "be",
      "flag": "be",
      "text": t("Belgium"),
    },
    {
      "key": "bz",
      "value": "bz",
      "flag": "bz",
      "text": t("Belize"),
    },
    {
      "key": "bj",
      "value": "bj",
      "flag": "bj",
      "text": t("Benin"),
    },
    {
      "key": "bm",
      "value": "bm",
      "flag": "bm",
      "text": t("Bermuda"),
    },
    {
      "key": "bt",
      "value": "bt",
      "flag": "bt",
      "text": t("Bhutan"),
    },
    {
      "key": "bo",
      "value": "bo",
      "flag": "bo",
      "text": t("Bolivia, Plurinational State of"),
    },
    {
      "key": "bq",
      "value": "bq",
      "flag": "bq",
      "text": t("Bonaire, Sint Eustatius and Saba"),
    },
    {
      "key": "ba",
      "value": "ba",
      "flag": "ba",
      "text": t("Bosnia and Herzegovina"),
    },
    {
      "key": "bw",
      "value": "bw",
      "flag": "bw",
      "text": t("Botswana"),
    },
    {
      "key": "bv",
      "value": "bv",
      "flag": "bv",
      "text": t("Bouvet Island"),
    },
    {
      "key": "br",
      "value": "br",
      "flag": "br",
      "text": t("Brazil"),
    },
    {
      "key": "io",
      "value": "io",
      "flag": "io",
      "text": t("British Indian Ocean Territory"),
    },
    {
      "key": "bn",
      "value": "bn",
      "flag": "bn",
      "text": t("Brunei Darussalam"),
    },
    {
      "key": "bg",
      "value": "bg",
      "flag": "bg",
      "text": t("Bulgaria"),
    },
    {
      "key": "bf",
      "value": "bf",
      "flag": "bf",
      "text": t("Burkina Faso"),
    },
    {
      "key": "bi",
      "value": "bi",
      "flag": "bi",
      "text": t("Burundi"),
    },
    {
      "key": "cv",
      "value": "cv",
      "flag": "cv",
      "text": t("Cabo Verde"),
    },
    {
      "key": "kh",
      "value": "kh",
      "flag": "kh",
      "text": t("Cambodia"),
    },
    {
      "key": "cm",
      "value": "cm",
      "flag": "cm",
      "text": t("Cameroon"),
    },
    {
      "key": "ca",
      "value": "ca",
      "flag": "ca",
      "text": t("Canada"),
    },
    {
      "key": "ky",
      "value": "ky",
      "flag": "ky",
      "text": t("Cayman Islands"),
    },
    {
      "key": "cf",
      "value": "cf",
      "flag": "cf",
      "text": t("Central African Republic"),
    },
    {
      "key": "td",
      "value": "td",
      "flag": "td",
      "text": t("Chad"),
    },
    {
      "key": "cl",
      "value": "cl",
      "flag": "cl",
      "text": t("Chile"),
    },
    {
      "key": "cn",
      "value": "cn",
      "flag": "cn",
      "text": t("China"),
    },
    {
      "key": "cx",
      "value": "cx",
      "flag": "cx",
      "text": t("Christmas Island"),
    },
    {
      "key": "cc",
      "value": "cc",
      "flag": "cc",
      "text": t("Cocos (Keeling) Islands"),
    },
    {
      "key": "co",
      "value": "co",
      "flag": "co",
      "text": t("Colombia"),
    },
    {
      "key": "km",
      "value": "km",
      "flag": "km",
      "text": t("Comoros"),
    },
    {
      "key": "cg",
      "value": "cg",
      "flag": "cg",
      "text": t("Congo"),
    },
    {
      "key": "cd",
      "value": "cd",
      "flag": "cd",
      "text": t("Congo, The Democratic Republic of the"),
    },
    {
      "key": "ck",
      "value": "ck",
      "flag": "ck",
      "text": t("Cook Islands"),
    },
    {
      "key": "cr",
      "value": "cr",
      "flag": "cr",
      "text": t("Costa Rica"),
    },
    {
      "key": "hr",
      "value": "hr",
      "flag": "hr",
      "text": t("Croatia"),
    },
    {
      "key": "cu",
      "value": "cu",
      "flag": "cu",
      "text": t("Cuba"),
    },
    {
      "key": "cw",
      "value": "cw",
      "flag": "cw",
      "text": t("Curaçao"),
    },
    {
      "key": "cy",
      "value": "cy",
      "flag": "cy",
      "text": t("Cyprus"),
    },
    {
      "key": "cz",
      "value": "cz",
      "flag": "cz",
      "text": t("Czechia"),
    },
    {
      "key": "ci",
      "value": "ci",
      "flag": "ci",
      "text": t("Côte d'Ivoire"),
    },
    {
      "key": "dk",
      "value": "dk",
      "flag": "dk",
      "text": t("Denmark"),
    },
    {
      "key": "dj",
      "value": "dj",
      "flag": "dj",
      "text": t("Djibouti"),
    },
    {
      "key": "dm",
      "value": "dm",
      "flag": "dm",
      "text": t("Dominica"),
    },
    {
      "key": "do",
      "value": "do",
      "flag": "do",
      "text": t("Dominican Republic"),
    },
    {
      "key": "ec",
      "value": "ec",
      "flag": "ec",
      "text": t("Ecuador"),
    },
    {
      "key": "eg",
      "value": "eg",
      "flag": "eg",
      "text": t("Egypt"),
    },
    {
      "key": "sv",
      "value": "sv",
      "flag": "sv",
      "text": t("El Salvador"),
    },
    {
      "key": "gq",
      "value": "gq",
      "flag": "gq",
      "text": t("Equatorial Guinea"),
    },
    {
      "key": "er",
      "value": "er",
      "flag": "er",
      "text": t("Eritrea"),
    },
    {
      "key": "ee",
      "value": "ee",
      "flag": "ee",
      "text": t("Estonia"),
    },
    {
      "key": "sz",
      "value": "sz",
      "flag": "sz",
      "text": t("Eswatini"),
    },
    {
      "key": "et",
      "value": "et",
      "flag": "et",
      "text": t("Ethiopia"),
    },
    {
      "key": "fk",
      "value": "fk",
      "flag": "fk",
      "text": t("Falkland Islands (Malvinas)"),
    },
    {
      "key": "fo",
      "value": "fo",
      "flag": "fo",
      "text": t("Faroe Islands"),
    },
    {
      "key": "fj",
      "value": "fj",
      "flag": "fj",
      "text": t("Fiji"),
    },
    {
      "key": "fi",
      "value": "fi",
      "flag": "fi",
      "text": t("Finland"),
    },
    {
      "key": "fr",
      "value": "fr",
      "flag": "fr",
      "text": t("France"),
    },
    {
      "key": "gf",
      "value": "gf",
      "flag": "gf",
      "text": t("French Guiana"),
    },
    {
      "key": "pf",
      "value": "pf",
      "flag": "pf",
      "text": t("French Polynesia"),
    },
    {
      "key": "tf",
      "value": "tf",
      "flag": "tf",
      "text": t("French Southern Territories"),
    },
    {
      "key": "ga",
      "value": "ga",
      "flag": "ga",
      "text": t("Gabon"),
    },
    {
      "key": "gm",
      "value": "gm",
      "flag": "gm",
      "text": t("Gambia"),
    },
    {
      "key": "ge",
      "value": "ge",
      "flag": "ge",
      "text": t("Georgia"),
    },
    {
      "key": "de",
      "value": "de",
      "flag": "de",
      "text": t("Germany"),
    },
    {
      "key": "gh",
      "value": "gh",
      "flag": "gh",
      "text": t("Ghana"),
    },
    {
      "key": "gi",
      "value": "gi",
      "flag": "gi",
      "text": t("Gibraltar"),
    },
    {
      "key": "gr",
      "value": "gr",
      "flag": "gr",
      "text": t("Greece"),
    },
    {
      "key": "gl",
      "value": "gl",
      "flag": "gl",
      "text": t("Greenland"),
    },
    {
      "key": "gd",
      "value": "gd",
      "flag": "gd",
      "text": t("Grenada"),
    },
    {
      "key": "gp",
      "value": "gp",
      "flag": "gp",
      "text": t("Guadeloupe"),
    },
    {
      "key": "gu",
      "value": "gu",
      "flag": "gu",
      "text": t("Guam"),
    },
    {
      "key": "gt",
      "value": "gt",
      "flag": "gt",
      "text": t("Guatemala"),
    },
    {
      "key": "gg",
      "value": "gg",
      "flag": "gg",
      "text": t("Guernsey"),
    },
    {
      "key": "gn",
      "value": "gn",
      "flag": "gn",
      "text": t("Guinea"),
    },
    {
      "key": "gw",
      "value": "gw",
      "flag": "gw",
      "text": t("Guinea-Bissau"),
    },
    {
      "key": "gy",
      "value": "gy",
      "flag": "gy",
      "text": t("Guyana"),
    },
    {
      "key": "ht",
      "value": "ht",
      "flag": "ht",
      "text": t("Haiti"),
    },
    {
      "key": "hm",
      "value": "hm",
      "flag": "hm",
      "text": t("Heard Island and McDonald Islands"),
    },
    {
      "key": "va",
      "value": "va",
      "flag": "va",
      "text": t("Holy See (Vatican City State)"),
    },
    {
      "key": "hn",
      "value": "hn",
      "flag": "hn",
      "text": t("Honduras"),
    },
    {
      "key": "hk",
      "value": "hk",
      "flag": "hk",
      "text": t("Hong Kong"),
    },
    {
      "key": "hu",
      "value": "hu",
      "flag": "hu",
      "text": t("Hungary"),
    },
    {
      "key": "is",
      "value": "is",
      "flag": "is",
      "text": t("Iceland"),
    },
    {
      "key": "in",
      "value": "in",
      "flag": "in",
      "text": t("India"),
    },
    {
      "key": "id",
      "value": "id",
      "flag": "id",
      "text": t("Indonesia"),
    },
    {
      "key": "ir",
      "value": "ir",
      "flag": "ir",
      "text": t("Iran, Islamic Republic of"),
    },
    {
      "key": "iq",
      "value": "iq",
      "flag": "iq",
      "text": t("Iraq"),
    },
    {
      "key": "ie",
      "value": "ie",
      "flag": "ie",
      "text": t("Ireland"),
    },
    {
      "key": "im",
      "value": "im",
      "flag": "im",
      "text": t("Isle of Man"),
    },
    {
      "key": "il",
      "value": "il",
      "flag": "il",
      "text": t("Israel"),
    },
    {
      "key": "it",
      "value": "it",
      "flag": "it",
      "text": t("Italy"),
    },
    {
      "key": "jm",
      "value": "jm",
      "flag": "jm",
      "text": t("Jamaica"),
    },
    {
      "key": "jp",
      "value": "jp",
      "flag": "jp",
      "text": t("Japan"),
    },
    {
      "key": "je",
      "value": "je",
      "flag": "je",
      "text": t("Jersey"),
    },
    {
      "key": "jo",
      "value": "jo",
      "flag": "jo",
      "text": t("Jordan"),
    },
    {
      "key": "kz",
      "value": "kz",
      "flag": "kz",
      "text": t("Kazakhstan"),
    },
    {
      "key": "ke",
      "value": "ke",
      "flag": "ke",
      "text": t("Kenya"),
    },
    {
      "key": "ki",
      "value": "ki",
      "flag": "ki",
      "text": t("Kiribati"),
    },
    {
      "key": "kp",
      "value": "kp",
      "flag": "kp",
      "text": t("Korea, Democratic People's Republic of"),
    },
    {
      "key": "kr",
      "value": "kr",
      "flag": "kr",
      "text": t("Korea, Republic of"),
    },
    {
      "key": "kw",
      "value": "kw",
      "flag": "kw",
      "text": t("Kuwait"),
    },
    {
      "key": "kg",
      "value": "kg",
      "flag": "kg",
      "text": t("Kyrgyzstan"),
    },
    {
      "key": "la",
      "value": "la",
      "flag": "la",
      "text": t("Lao People's Democratic Republic"),
    },
    {
      "key": "lv",
      "value": "lv",
      "flag": "lv",
      "text": t("Latvia"),
    },
    {
      "key": "lb",
      "value": "lb",
      "flag": "lb",
      "text": t("Lebanon"),
    },
    {
      "key": "ls",
      "value": "ls",
      "flag": "ls",
      "text": t("Lesotho"),
    },
    {
      "key": "lr",
      "value": "lr",
      "flag": "lr",
      "text": t("Liberia"),
    },
    {
      "key": "ly",
      "value": "ly",
      "flag": "ly",
      "text": t("Libya"),
    },
    {
      "key": "li",
      "value": "li",
      "flag": "li",
      "text": t("Liechtenstein"),
    },
    {
      "key": "lt",
      "value": "lt",
      "flag": "lt",
      "text": t("Lithuania"),
    },
    {
      "key": "lu",
      "value": "lu",
      "flag": "lu",
      "text": t("Luxembourg"),
    },
    {
      "key": "mo",
      "value": "mo",
      "flag": "mo",
      "text": t("Macao"),
    },
    {
      "key": "mg",
      "value": "mg",
      "flag": "mg",
      "text": t("Madagascar"),
    },
    {
      "key": "mw",
      "value": "mw",
      "flag": "mw",
      "text": t("Malawi"),
    },
    {
      "key": "my",
      "value": "my",
      "flag": "my",
      "text": t("Malaysia"),
    },
    {
      "key": "mv",
      "value": "mv",
      "flag": "mv",
      "text": t("Maldives"),
    },
    {
      "key": "ml",
      "value": "ml",
      "flag": "ml",
      "text": t("Mali"),
    },
    {
      "key": "mt",
      "value": "mt",
      "flag": "mt",
      "text": t("Malta"),
    },
    {
      "key": "mh",
      "value": "mh",
      "flag": "mh",
      "text": t("Marshall Islands"),
    },
    {
      "key": "mq",
      "value": "mq",
      "flag": "mq",
      "text": t("Martinique"),
    },
    {
      "key": "mr",
      "value": "mr",
      "flag": "mr",
      "text": t("Mauritania"),
    },
    {
      "key": "mu",
      "value": "mu",
      "flag": "mu",
      "text": t("Mauritius"),
    },
    {
      "key": "yt",
      "value": "yt",
      "flag": "yt",
      "text": t("Mayotte"),
    },
    {
      "key": "mx",
      "value": "mx",
      "flag": "mx",
      "text": t("Mexico"),
    },
    {
      "key": "fm",
      "value": "fm",
      "flag": "fm",
      "text": t("Micronesia, Federated States of"),
    },
    {
      "key": "md",
      "value": "md",
      "flag": "md",
      "text": t("Moldova, Republic of"),
    },
    {
      "key": "mc",
      "value": "mc",
      "flag": "mc",
      "text": t("Monaco"),
    },
    {
      "key": "mn",
      "value": "mn",
      "flag": "mn",
      "text": t("Mongolia"),
    },
    {
      "key": "me",
      "value": "me",
      "flag": "me",
      "text": t("Montenegro"),
    },
    {
      "key": "ms",
      "value": "ms",
      "flag": "ms",
      "text": t("Montserrat"),
    },
    {
      "key": "ma",
      "value": "ma",
      "flag": "ma",
      "text": t("Morocco"),
    },
    {
      "key": "mz",
      "value": "mz",
      "flag": "mz",
      "text": t("Mozambique"),
    },
    {
      "key": "mm",
      "value": "mm",
      "flag": "mm",
      "text": t("Myanmar"),
    },
    {
      "key": "na",
      "value": "na",
      "flag": "na",
      "text": t("Namibia"),
    },
    {
      "key": "nr",
      "value": "nr",
      "flag": "nr",
      "text": t("Nauru"),
    },
    {
      "key": "np",
      "value": "np",
      "flag": "np",
      "text": t("Nepal"),
    },
    {
      "key": "nl",
      "value": "nl",
      "flag": "nl",
      "text": t("Netherlands"),
    },
    {
      "key": "nc",
      "value": "nc",
      "flag": "nc",
      "text": t("New Caledonia"),
    },
    {
      "key": "nz",
      "value": "nz",
      "flag": "nz",
      "text": t("New Zealand"),
    },
    {
      "key": "ni",
      "value": "ni",
      "flag": "ni",
      "text": t("Nicaragua"),
    },
    {
      "key": "ne",
      "value": "ne",
      "flag": "ne",
      "text": t("Niger"),
    },
    {
      "key": "ng",
      "value": "ng",
      "flag": "ng",
      "text": t("Nigeria"),
    },
    {
      "key": "nu",
      "value": "nu",
      "flag": "nu",
      "text": t("Niue"),
    },
    {
      "key": "nf",
      "value": "nf",
      "flag": "nf",
      "text": t("Norfolk Island"),
    },
    {
      "key": "mk",
      "value": "mk",
      "flag": "mk",
      "text": t("North Macedonia"),
    },
    {
      "key": "mp",
      "value": "mp",
      "flag": "mp",
      "text": t("Northern Mariana Islands"),
    },
    {
      "key": "no",
      "value": "no",
      "flag": "no",
      "text": t("Norway"),
    },
    {
      "key": "om",
      "value": "om",
      "flag": "om",
      "text": t("Oman"),
    },
    {
      "key": "pk",
      "value": "pk",
      "flag": "pk",
      "text": t("Pakistan"),
    },
    {
      "key": "pw",
      "value": "pw",
      "flag": "pw",
      "text": t("Palau"),
    },
    {
      "key": "ps",
      "value": "ps",
      "flag": "ps",
      "text": t("Palestine, State of"),
    },
    {
      "key": "pa",
      "value": "pa",
      "flag": "pa",
      "text": t("Panama"),
    },
    {
      "key": "pg",
      "value": "pg",
      "flag": "pg",
      "text": t("Papua New Guinea"),
    },
    {
      "key": "py",
      "value": "py",
      "flag": "py",
      "text": t("Paraguay"),
    },
    {
      "key": "pe",
      "value": "pe",
      "flag": "pe",
      "text": t("Peru"),
    },
    {
      "key": "ph",
      "value": "ph",
      "flag": "ph",
      "text": t("Philippines"),
    },
    {
      "key": "pn",
      "value": "pn",
      "flag": "pn",
      "text": t("Pitcairn"),
    },
    {
      "key": "pl",
      "value": "pl",
      "flag": "pl",
      "text": t("Poland"),
    },
    {
      "key": "pt",
      "value": "pt",
      "flag": "pt",
      "text": t("Portugal"),
    },
    {
      "key": "pr",
      "value": "pr",
      "flag": "pr",
      "text": t("Puerto Rico"),
    },
    {
      "key": "qa",
      "value": "qa",
      "flag": "qa",
      "text": t("Qatar"),
    },
    {
      "key": "ro",
      "value": "ro",
      "flag": "ro",
      "text": t("Romania"),
    },
    {
      "key": "ru",
      "value": "ru",
      "flag": "ru",
      "text": t("Russian Federation"),
    },
    {
      "key": "rw",
      "value": "rw",
      "flag": "rw",
      "text": t("Rwanda"),
    },
    {
      "key": "re",
      "value": "re",
      "flag": "re",
      "text": t("Réunion"),
    },
    {
      "key": "bl",
      "value": "bl",
      "flag": "bl",
      "text": t("Saint Barthélemy"),
    },
    {
      "key": "sh",
      "value": "sh",
      "flag": "sh",
      "text": t("Saint Helena, Ascension and Tristan da Cunha"),
    },
    {
      "key": "kn",
      "value": "kn",
      "flag": "kn",
      "text": t("Saint Kitts and Nevis"),
    },
    {
      "key": "lc",
      "value": "lc",
      "flag": "lc",
      "text": t("Saint Lucia"),
    },
    {
      "key": "mf",
      "value": "mf",
      "flag": "mf",
      "text": t("Saint Martin (French part)"),
    },
    {
      "key": "pm",
      "value": "pm",
      "flag": "pm",
      "text": t("Saint Pierre and Miquelon"),
    },
    {
      "key": "vc",
      "value": "vc",
      "flag": "vc",
      "text": t("Saint Vincent and the Grenadines"),
    },
    {
      "key": "ws",
      "value": "ws",
      "flag": "ws",
      "text": t("Samoa"),
    },
    {
      "key": "sm",
      "value": "sm",
      "flag": "sm",
      "text": t("San Marino"),
    },
    {
      "key": "st",
      "value": "st",
      "flag": "st",
      "text": t("Sao Tome and Principe"),
    },
    {
      "key": "sa",
      "value": "sa",
      "flag": "sa",
      "text": t("Saudi Arabia"),
    },
    {
      "key": "sn",
      "value": "sn",
      "flag": "sn",
      "text": t("Senegal"),
    },
    {
      "key": "rs",
      "value": "rs",
      "flag": "rs",
      "text": t("Serbia"),
    },
    {
      "key": "sc",
      "value": "sc",
      "flag": "sc",
      "text": t("Seychelles"),
    },
    {
      "key": "sl",
      "value": "sl",
      "flag": "sl",
      "text": t("Sierra Leone"),
    },
    {
      "key": "sg",
      "value": "sg",
      "flag": "sg",
      "text": t("Singapore"),
    },
    {
      "key": "sx",
      "value": "sx",
      "flag": "sx",
      "text": t("Sint Maarten (Dutch part)"),
    },
    {
      "key": "sk",
      "value": "sk",
      "flag": "sk",
      "text": t("Slovakia"),
    },
    {
      "key": "si",
      "value": "si",
      "flag": "si",
      "text": t("Slovenia"),
    },
    {
      "key": "sb",
      "value": "sb",
      "flag": "sb",
      "text": t("Solomon Islands"),
    },
    {
      "key": "so",
      "value": "so",
      "flag": "so",
      "text": t("Somalia"),
    },
    {
      "key": "za",
      "value": "za",
      "flag": "za",
      "text": t("South Africa"),
    },
    {
      "key": "gs",
      "value": "gs",
      "flag": "gs",
      "text": t("South Georgia and the South Sandwich Islands"),
    },
    {
      "key": "ss",
      "value": "ss",
      "flag": "ss",
      "text": t("South Sudan"),
    },
    {
      "key": "es",
      "value": "es",
      "flag": "es",
      "text": t("Spain"),
    },
    {
      "key": "lk",
      "value": "lk",
      "flag": "lk",
      "text": t("Sri Lanka"),
    },
    {
      "key": "sd",
      "value": "sd",
      "flag": "sd",
      "text": t("Sudan"),
    },
    {
      "key": "sr",
      "value": "sr",
      "flag": "sr",
      "text": t("Suriname"),
    },
    {
      "key": "sj",
      "value": "sj",
      "flag": "sj",
      "text": t("Svalbard and Jan Mayen"),
    },
    {
      "key": "se",
      "value": "se",
      "flag": "se",
      "text": t("Sweden"),
    },
    {
      "key": "ch",
      "value": "ch",
      "flag": "ch",
      "text": t("Switzerland"),
    },
    {
      "key": "sy",
      "value": "sy",
      "flag": "sy",
      "text": t("Syrian Arab Republic"),
    },
    {
      "key": "tw",
      "value": "tw",
      "flag": "tw",
      "text": t("Taiwan, Province of China"),
    },
    {
      "key": "tj",
      "value": "tj",
      "flag": "tj",
      "text": t("Tajikistan"),
    },
    {
      "key": "tz",
      "value": "tz",
      "flag": "tz",
      "text": t("Tanzania, United Republic of"),
    },
    {
      "key": "th",
      "value": "th",
      "flag": "th",
      "text": t("Thailand"),
    },
    {
      "key": "tl",
      "value": "tl",
      "flag": "tl",
      "text": t("Timor-Leste"),
    },
    {
      "key": "tg",
      "value": "tg",
      "flag": "tg",
      "text": t("Togo"),
    },
    {
      "key": "tk",
      "value": "tk",
      "flag": "tk",
      "text": t("Tokelau"),
    },
    {
      "key": "to",
      "value": "to",
      "flag": "to",
      "text": t("Tonga"),
    },
    {
      "key": "tt",
      "value": "tt",
      "flag": "tt",
      "text": t("Trinidad and Tobago"),
    },
    {
      "key": "tn",
      "value": "tn",
      "flag": "tn",
      "text": t("Tunisia"),
    },
    {
      "key": "tr",
      "value": "tr",
      "flag": "tr",
      "text": t("Turkey"),
    },
    {
      "key": "tm",
      "value": "tm",
      "flag": "tm",
      "text": t("Turkmenistan"),
    },
    {
      "key": "tc",
      "value": "tc",
      "flag": "tc",
      "text": t("Turks and Caicos Islands"),
    },
    {
      "key": "tv",
      "value": "tv",
      "flag": "tv",
      "text": t("Tuvalu"),
    },
    {
      "key": "ug",
      "value": "ug",
      "flag": "ug",
      "text": t("Uganda"),
    },
    {
      "key": "ua",
      "value": "ua",
      "flag": "ua",
      "text": t("Ukraine"),
    },
    {
      "key": "ae",
      "value": "ae",
      "flag": "ae",
      "text": t("United Arab Emirates"),
    },
    {
      "key": "gb",
      "value": "gb",
      "flag": "gb",
      "text": t("United Kingdom"),
    },
    {
      "key": "us",
      "value": "us",
      "flag": "us",
      "text": t("United States"),
    },
    {
      "key": "um",
      "value": "um",
      "flag": "um",
      "text": t("United States Minor Outlying Islands"),
    },
    {
      "key": "uy",
      "value": "uy",
      "flag": "uy",
      "text": t("Uruguay"),
    },
    {
      "key": "uz",
      "value": "uz",
      "flag": "uz",
      "text": t("Uzbekistan"),
    },
    {
      "key": "vu",
      "value": "vu",
      "flag": "vu",
      "text": t("Vanuatu"),
    },
    {
      "key": "ve",
      "value": "ve",
      "flag": "ve",
      "text": t("Venezuela, Bolivarian Republic of"),
    },
    {
      "key": "vn",
      "value": "vn",
      "flag": "vn",
      "text": t("Viet Nam"),
    },
    {
      "key": "vg",
      "value": "vg",
      "flag": "vg",
      "text": t("Virgin Islands, British"),
    },
    {
      "key": "vi",
      "value": "vi",
      "flag": "vi",
      "text": t("Virgin Islands, U.S."),
    },
    {
      "key": "wf",
      "value": "wf",
      "flag": "wf",
      "text": t("Wallis and Futuna"),
    },
    {
      "key": "eh",
      "value": "eh",
      "flag": "eh",
      "text": t("Western Sahara"),
    },
    {
      "key": "ye",
      "value": "ye",
      "flag": "ye",
      "text": t("Yemen"),
    },
    {
      "key": "zm",
      "value": "zm",
      "flag": "zm",
      "text": t("Zambia"),
    },
    {
      "key": "zw",
      "value": "zw",
      "flag": "zw",
      "text": t("Zimbabwe"),
    },
    {
      "key": "ax",
      "value": "ax",
      "flag": "ax",
      "text": t("Åland Islands"),
    }
  ];
}

export function CountrySelector ({ fluid = false } = {}) {
  const { t } = useTranslation('CountrySelector')
  const { country, setCountry } = useIndexContext()
  const countries = useCountries()
  return (
    <Dropdown
      placeholder={t('Select Country')}
      fluid={fluid}
      search
      selection
      options={countries}
      value={country}
      onChange={(e, { value }) => setCountry(value)}
    />
  )
}

export function CountryFormField ({ fluid = false, countryError = '' } = {}) {
  return (
    <Form.Field error={!isEmpty(countryError)}>
      <CountrySelector fluid={fluid}/>
      {!isEmpty(countryError) && (
        <Label basic color='red' pointing>
          {countryError}
        </Label>
      )}
    </Form.Field>
  )
}
